# Default values for registration-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: skabrits/registration-backend
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []

app:
  db-password: bW9uZ29kYjovL3Jvb3Q6UFU4WU5QOUZCN0Btb25nb2RiLmRiLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNw==

port: 8000

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  path: registration
