apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "registration-backend.fullname" . }}
  labels:
    {{- include "registration-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "registration-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "registration-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          env:
          - name: "DB_URL"
            valueFrom:
              secretKeyRef:
                key: db_conection_string
                name: {{ include "registration-backend.fullname" . }}-db-password
          - name: "FRONT_ENDPOINT"
            valueFrom:
              configMapKeyRef:
                key: front_endpoint
                name: {{ include "registration-backend.fullname" . }}-configmap
          volumeMounts:
          - mountPath: "/app/files"
            name: file-storage
      volumes:
      - name: file-storage
        persistentVolumeClaim:
          claimName: {{ include "registration-backend.fullname" . }}-pvc
