kind: Secret
metadata:
  name: {{ include "registration-backend.fullname" . }}-db-password
apiVersion: v1
data:
  db_conection_string: bW9uZ29kYjovL3Jvb3Q6UFU4WU5QOUZCN0Btb25nb2RiLmRiLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNw==