apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  source:
    path: "backend/src/registration/helm/registration-backend"
    repoURL: https://github.com/skabrits/Microservice-app.git
    targetRevision: "main"
    helm:
      releaseName: backend
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "dev"